// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameroom.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomPlayer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Country              int32    `protobuf:"varint,4,opt,name=Country,proto3" json:"Country,omitempty"`
	Trophies             int32    `protobuf:"varint,5,opt,name=Trophies,proto3" json:"Trophies,omitempty"`
	Equips               []int32  `protobuf:"varint,6,rep,packed,name=Equips,proto3" json:"Equips,omitempty"`
	Head                 int32    `protobuf:"varint,7,opt,name=Head,proto3" json:"Head,omitempty"`
	Order                int32    `protobuf:"varint,8,opt,name=Order,proto3" json:"Order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPlayer) Reset()         { *m = RoomPlayer{} }
func (m *RoomPlayer) String() string { return proto.CompactTextString(m) }
func (*RoomPlayer) ProtoMessage()    {}
func (*RoomPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2efe3966a9011ac, []int{0}
}

func (m *RoomPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayer.Unmarshal(m, b)
}
func (m *RoomPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayer.Marshal(b, m, deterministic)
}
func (m *RoomPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayer.Merge(m, src)
}
func (m *RoomPlayer) XXX_Size() int {
	return xxx_messageInfo_RoomPlayer.Size(m)
}
func (m *RoomPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayer proto.InternalMessageInfo

func (m *RoomPlayer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomPlayer) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RoomPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomPlayer) GetCountry() int32 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *RoomPlayer) GetTrophies() int32 {
	if m != nil {
		return m.Trophies
	}
	return 0
}

func (m *RoomPlayer) GetEquips() []int32 {
	if m != nil {
		return m.Equips
	}
	return nil
}

func (m *RoomPlayer) GetHead() int32 {
	if m != nil {
		return m.Head
	}
	return 0
}

func (m *RoomPlayer) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type GameRoomReq struct {
	//int32 Id = 1;
	Mode  int32 `protobuf:"varint,1,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Stage int32 `protobuf:"varint,2,opt,name=Stage,proto3" json:"Stage,omitempty"`
	//int32 LevId = 4;
	Players              []*RoomPlayer `protobuf:"bytes,3,rep,name=Players,proto3" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameRoomReq) Reset()         { *m = GameRoomReq{} }
func (m *GameRoomReq) String() string { return proto.CompactTextString(m) }
func (*GameRoomReq) ProtoMessage()    {}
func (*GameRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2efe3966a9011ac, []int{1}
}

func (m *GameRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRoomReq.Unmarshal(m, b)
}
func (m *GameRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRoomReq.Marshal(b, m, deterministic)
}
func (m *GameRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRoomReq.Merge(m, src)
}
func (m *GameRoomReq) XXX_Size() int {
	return xxx_messageInfo_GameRoomReq.Size(m)
}
func (m *GameRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_GameRoomReq proto.InternalMessageInfo

func (m *GameRoomReq) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *GameRoomReq) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *GameRoomReq) GetPlayers() []*RoomPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

type GameRoomResp struct {
	Id                   uint64        `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Mode                 int32         `protobuf:"varint,2,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Stage                int32         `protobuf:"varint,3,opt,name=Stage,proto3" json:"Stage,omitempty"`
	LevId                int32         `protobuf:"varint,4,opt,name=LevId,proto3" json:"LevId,omitempty"`
	Players              []*RoomPlayer `protobuf:"bytes,5,rep,name=Players,proto3" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameRoomResp) Reset()         { *m = GameRoomResp{} }
func (m *GameRoomResp) String() string { return proto.CompactTextString(m) }
func (*GameRoomResp) ProtoMessage()    {}
func (*GameRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2efe3966a9011ac, []int{2}
}

func (m *GameRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRoomResp.Unmarshal(m, b)
}
func (m *GameRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRoomResp.Marshal(b, m, deterministic)
}
func (m *GameRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRoomResp.Merge(m, src)
}
func (m *GameRoomResp) XXX_Size() int {
	return xxx_messageInfo_GameRoomResp.Size(m)
}
func (m *GameRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_GameRoomResp proto.InternalMessageInfo

func (m *GameRoomResp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameRoomResp) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *GameRoomResp) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *GameRoomResp) GetLevId() int32 {
	if m != nil {
		return m.LevId
	}
	return 0
}

func (m *GameRoomResp) GetPlayers() []*RoomPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

type JoinRoomReq struct {
	RoomId               uint64   `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	PlayerId             int32    `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2efe3966a9011ac, []int{3}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

func (m *JoinRoomReq) GetRoomId() uint64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomReq) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type JoinRoomResp struct {
	IsReady              bool     `protobuf:"varint,3,opt,name=IsReady,proto3" json:"IsReady,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResp) Reset()         { *m = JoinRoomResp{} }
func (m *JoinRoomResp) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResp) ProtoMessage()    {}
func (*JoinRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2efe3966a9011ac, []int{4}
}

func (m *JoinRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResp.Unmarshal(m, b)
}
func (m *JoinRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResp.Marshal(b, m, deterministic)
}
func (m *JoinRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResp.Merge(m, src)
}
func (m *JoinRoomResp) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResp.Size(m)
}
func (m *JoinRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResp proto.InternalMessageInfo

func (m *JoinRoomResp) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func init() {
	proto.RegisterType((*RoomPlayer)(nil), "protos.RoomPlayer")
	proto.RegisterType((*GameRoomReq)(nil), "protos.GameRoomReq")
	proto.RegisterType((*GameRoomResp)(nil), "protos.GameRoomResp")
	proto.RegisterType((*JoinRoomReq)(nil), "protos.JoinRoomReq")
	proto.RegisterType((*JoinRoomResp)(nil), "protos.JoinRoomResp")
}

func init() { proto.RegisterFile("gameroom.proto", fileDescriptor_a2efe3966a9011ac) }

var fileDescriptor_a2efe3966a9011ac = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0xc6, 0xb3, 0xbb, 0x74, 0xc1, 0x81, 0x70, 0x68, 0x08, 0x69, 0x3c, 0x6d, 0xf6, 0xb4, 0x07,
	0xc3, 0x41, 0x9f, 0x80, 0x18, 0xa3, 0x6b, 0xfc, 0x97, 0xea, 0x0b, 0x54, 0x3a, 0x41, 0x12, 0x97,
	0x2e, 0x2d, 0x98, 0xf0, 0x0e, 0x3e, 0x95, 0x4f, 0x66, 0x3a, 0xdd, 0x02, 0x07, 0x13, 0x4f, 0xcc,
	0xaf, 0x9d, 0xe9, 0x7c, 0xdf, 0xc7, 0xc2, 0x78, 0xa9, 0x1a, 0xb4, 0xc6, 0x34, 0xb3, 0xd6, 0x9a,
	0xad, 0xe1, 0x39, 0xfd, 0xb8, 0xf2, 0x27, 0x01, 0x90, 0xc6, 0x34, 0x2f, 0x9f, 0x6a, 0x8f, 0x96,
	0x8f, 0x21, 0xad, 0xb5, 0x48, 0x8a, 0xa4, 0x62, 0x32, 0xad, 0x35, 0x17, 0xd0, 0x9f, 0x2f, 0x16,
	0x66, 0xb7, 0xde, 0x8a, 0xb4, 0x48, 0xaa, 0x33, 0x19, 0x91, 0x73, 0xe8, 0x3d, 0xa9, 0x06, 0x45,
	0x46, 0xc7, 0x54, 0xfb, 0xee, 0x6b, 0x7f, 0x69, 0xf7, 0xa2, 0x47, 0x4f, 0x44, 0xe4, 0xe7, 0x30,
	0x78, 0xb3, 0xa6, 0xfd, 0x58, 0xa1, 0x13, 0x8c, 0xae, 0x0e, 0xcc, 0xa7, 0x90, 0xdf, 0x6c, 0x76,
	0xab, 0xd6, 0x89, 0xbc, 0xc8, 0x2a, 0x26, 0x3b, 0xf2, 0x1b, 0xee, 0x50, 0x69, 0xd1, 0xa7, 0x7e,
	0xaa, 0xf9, 0x04, 0xd8, 0xb3, 0xd5, 0x68, 0xc5, 0x80, 0x0e, 0x03, 0x94, 0x08, 0xc3, 0x5b, 0xd5,
	0xa0, 0xf7, 0x21, 0x71, 0xe3, 0x07, 0x1f, 0x8d, 0xc6, 0xce, 0x06, 0xd5, 0x7e, 0xf0, 0x75, 0xab,
	0x96, 0x48, 0x36, 0x98, 0x0c, 0xc0, 0x2f, 0xa0, 0x1f, 0x8c, 0x3b, 0x91, 0x15, 0x59, 0x35, 0xbc,
	0xe4, 0x21, 0x1e, 0x37, 0x3b, 0x66, 0x22, 0x63, 0x4b, 0xf9, 0x9d, 0xc0, 0xe8, 0xb8, 0xc7, 0xb5,
	0x27, 0x69, 0xf5, 0x28, 0xad, 0xb8, 0x38, 0xfd, 0x6b, 0x71, 0x76, 0xba, 0x78, 0x02, 0xec, 0x01,
	0xbf, 0x6a, 0xdd, 0xe5, 0x14, 0xe0, 0x54, 0x0e, 0xfb, 0x5f, 0xce, 0x1c, 0x86, 0xf7, 0x66, 0xb5,
	0x8e, 0xae, 0xa7, 0x90, 0xfb, 0xf2, 0x20, 0xa8, 0x23, 0x1f, 0x7d, 0x98, 0xa8, 0x75, 0x27, 0xec,
	0xc0, 0x65, 0x05, 0xa3, 0xe3, 0x13, 0xae, 0xf5, 0x7f, 0x60, 0xed, 0x24, 0x2a, 0xbd, 0x27, 0xb9,
	0x03, 0x19, 0xf1, 0x3d, 0x7c, 0x2f, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x83, 0x57,
	0xc9, 0x48, 0x02, 0x00, 0x00,
}
